version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 8081:8081
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    command: 'npm run dev'

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    command: 'sh -c "whoami && npm run dev"'

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  default:
    driver: bridge
